/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 註冊新的業務帳號。回傳使用者資料，不含密碼雜湊。
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 登入並取得 access token。
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description 回傳目前登入者的資料。前端可用它確認 token 是否還有效。
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        /** Create Lead */
        post: operations["create_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lead
         * @description 回傳單一 Lead，並附上互動紀錄 Timeline。
         */
        get: operations["get_lead_api_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        /** Delete Lead */
        delete: operations["delete_lead_api_v1_leads__lead_id__delete"];
        options?: never;
        head?: never;
        /** Update Lead */
        patch: operations["update_lead_api_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interactions */
        get: operations["list_interactions_api_v1_leads__lead_id__interactions_get"];
        put?: never;
        /** Create Interaction */
        post: operations["create_interaction_api_v1_leads__lead_id__interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/interactions/{interaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Interaction */
        delete: operations["delete_interaction_api_v1_leads__lead_id__interactions__interaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InteractionCreate */
        InteractionCreate: {
            type: components["schemas"]["InteractionType"];
            /** Content */
            content: string;
        };
        /** InteractionRead */
        InteractionRead: {
            /** Id */
            id: number;
            /** Lead Id */
            lead_id: number;
            type: components["schemas"]["InteractionType"];
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InteractionType
         * @description 業務與客戶的互動管道。
         * @enum {string}
         */
        InteractionType: "CALL" | "LINE" | "EMAIL" | "MEETING" | "VIEWING" | "NOTE";
        /** LeadCreate */
        LeadCreate: {
            /** Location */
            location?: string | null;
            /** Budget Min */
            budget_min?: number | null;
            /** Budget Max */
            budget_max?: number | null;
            /** Rooms */
            rooms?: number | null;
            /** Parking */
            parking?: boolean | null;
            purpose?: components["schemas"]["Purpose"] | null;
            /**
             * Purchase Timeline
             * @description 預計幾個月內購買
             */
            purchase_timeline?: number | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** @default OTHER */
            source: components["schemas"]["LeadSource"];
            /** Raw Requirement */
            raw_requirement?: string | null;
        };
        /**
         * LeadDetail
         * @description Lead Detail 頁專用：在基本資料之外，一併帶出互動紀錄 Timeline。
         *
         *     列表用 LeadRead（輕量），詳細頁用 LeadDetail（含 interactions），
         *     這樣列表 50 筆客戶時不會順便把幾百筆互動紀錄一起撈出來。
         */
        LeadDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            source: components["schemas"]["LeadSource"];
            status: components["schemas"]["LeadStatus"];
            /** Raw Requirement */
            raw_requirement: string | null;
            /** Location */
            location: string | null;
            /** Budget Min */
            budget_min: number | null;
            /** Budget Max */
            budget_max: number | null;
            /** Rooms */
            rooms: number | null;
            /** Parking */
            parking: boolean | null;
            purpose: components["schemas"]["Purpose"] | null;
            /** Purchase Timeline */
            purchase_timeline: number | null;
            /** Lead Score */
            lead_score: number | null;
            lead_level: components["schemas"]["LeadLevel"] | null;
            /** Owner Id */
            owner_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Interactions
             * @default []
             */
            interactions: components["schemas"]["InteractionRead"][];
        };
        /**
         * LeadLevel
         * @description 由 Lead Score 換算出的優先層級（Sprint 5 的 Scoring Engine 負責填）。
         * @enum {string}
         */
        LeadLevel: "HOT" | "WARM" | "COLD";
        /**
         * LeadListResponse
         * @description 列表一律包一層，日後要加 total / page 才不用改前端的解析方式。
         */
        LeadListResponse: {
            /** Items */
            items: components["schemas"]["LeadRead"][];
            /** Total */
            total: number;
        };
        /**
         * LeadRead
         * @description 回傳給前端的完整 Lead。
         */
        LeadRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            source: components["schemas"]["LeadSource"];
            status: components["schemas"]["LeadStatus"];
            /** Raw Requirement */
            raw_requirement: string | null;
            /** Location */
            location: string | null;
            /** Budget Min */
            budget_min: number | null;
            /** Budget Max */
            budget_max: number | null;
            /** Rooms */
            rooms: number | null;
            /** Parking */
            parking: boolean | null;
            purpose: components["schemas"]["Purpose"] | null;
            /** Purchase Timeline */
            purchase_timeline: number | null;
            /** Lead Score */
            lead_score: number | null;
            lead_level: components["schemas"]["LeadLevel"] | null;
            /** Owner Id */
            owner_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LeadSource
         * @description Lead 的來源管道。
         * @enum {string}
         */
        LeadSource: "WEB_FORM" | "PHONE" | "REFERRAL" | "WALK_IN" | "LINE" | "OTHER";
        /**
         * LeadStatus
         * @description Lead 在銷售漏斗中的位置（對應 Dashboard 的 Lead Funnel）。
         * @enum {string}
         */
        LeadStatus: "NEW" | "CONTACTED" | "INTERESTED" | "MEETING" | "NEGOTIATING" | "WON" | "LOST";
        /**
         * LeadUpdate
         * @description PATCH 用。所有欄位都是選填，只更新有帶的欄位。
         */
        LeadUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            source?: components["schemas"]["LeadSource"] | null;
            status?: components["schemas"]["LeadStatus"] | null;
            /** Raw Requirement */
            raw_requirement?: string | null;
            /** Location */
            location?: string | null;
            /** Budget Min */
            budget_min?: number | null;
            /** Budget Max */
            budget_max?: number | null;
            /** Rooms */
            rooms?: number | null;
            /** Parking */
            parking?: boolean | null;
            purpose?: components["schemas"]["Purpose"] | null;
            /** Purchase Timeline */
            purchase_timeline?: number | null;
        };
        /**
         * Purpose
         * @description 購屋目的。AI 解析自然語言後會填入這個欄位。
         * @enum {string}
         */
        Purpose: "SELF_USE" | "INVESTMENT" | "BOTH" | "UNKNOWN";
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserRead
         * @description 回傳給前端的使用者資料。
         *
         *     刻意不包含 password_hash —— schema 白名單就是最後一道防線，
         *     即使有人不小心把整個 model 丟出去，密碼雜湊也不會流出。
         */
        UserRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["LeadStatus"] | null;
                /** @description 比對姓名或電話 */
                keyword?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lead_api_v1_leads__lead_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_api_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interactions_api_v1_leads__lead_id__interactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interaction_api_v1_leads__lead_id__interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interaction_api_v1_leads__lead_id__interactions__interaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
                interaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
