"""add lead urgency

Revision ID: 3d6d5ed73e3a
Revises: 3e268d5bf865
Create Date: 2026-08-26 17:49:24.510421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6d5ed73e3a'
down_revision: Union[str, None] = '3e268d5bf865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('urgency', sa.Enum('HIGH', 'LOW', name='urgency', native_enum=False, length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'urgency')
    # ### end Alembic commands ###
