"""add ai parsing fields and ai_analysis table

Revision ID: 3e268d5bf865
Revises: b3e491d77bae
Create Date: 2026-08-26 10:06:49.023648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e268d5bf865'
down_revision: Union[str, None] = 'b3e491d77bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('parsed_result', sa.JSON(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('score_snapshot', sa.Integer(), nullable=True),
    sa.Column('level_snapshot', sa.String(length=10), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_lead_id'), 'ai_analysis', ['lead_id'], unique=False)
    # autogenerate 原本產生的是不帶 server_default 的 NOT NULL 欄位，
    # 那會在既有資料上直接失敗：舊的每一列都沒有值可填。
    # 補上 server_default，既有 lead 一律視為「預算不是概數」。
    op.add_column(
        'leads',
        sa.Column(
            'budget_is_approximate',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('leads', sa.Column('property_type', sa.Enum('ELEVATOR_BUILDING', 'LOW_RISE', 'APARTMENT', 'TOWNHOUSE', 'VILLA', 'STUDIO', name='propertytype', native_enum=False, length=20), nullable=True))
    op.add_column('leads', sa.Column('building_age_max', sa.Integer(), nullable=True, comment='可接受的屋齡上限（年）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'building_age_max')
    op.drop_column('leads', 'property_type')
    op.drop_column('leads', 'budget_is_approximate')
    op.drop_index(op.f('ix_ai_analysis_lead_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    # ### end Alembic commands ###
