"""add viewing_scheduled_at

Revision ID: ade829a9044a
Revises: b66c6d5969f3
Create Date: 2026-08-27 12:31:52.102096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade829a9044a'
down_revision: Union[str, None] = 'b66c6d5969f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('viewing_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_leads_viewing_scheduled_at'), 'leads', ['viewing_scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_viewing_scheduled_at'), table_name='leads')
    op.drop_column('leads', 'viewing_scheduled_at')
    # ### end Alembic commands ###
