"""make lead owner required and add index

Revision ID: b3e491d77bae
Revises: b85cf7453e2e
Create Date: 2026-08-24 13:08:48.450646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e491d77bae'
down_revision: Union[str, None] = 'b85cf7453e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """把 owner_id 改為必填，並加上索引。

    前提：leads 表中不能存在 owner_id 為 NULL 的資料，否則 alter_column 會失敗。
    本次執行時該表為空。若日後在有資料的環境套用，需先補上 owner_id
    （例如指派給某個預設帳號）再執行。

    索引的用途：資料隔離讓每一次查詢都帶 owner_id 條件，沒有索引會全表掃描。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.alter_column('leads', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
