"""add follow up reminder fields

Revision ID: b66c6d5969f3
Revises: 3d6d5ed73e3a
Create Date: 2026-08-26 21:20:19.180408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66c6d5969f3'
down_revision: Union[str, None] = '3d6d5ed73e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('next_follow_up_at', sa.Date(), nullable=True))
    op.add_column('leads', sa.Column('follow_up_muted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_leads_next_follow_up_at'), 'leads', ['next_follow_up_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_next_follow_up_at'), table_name='leads')
    op.drop_column('leads', 'follow_up_muted')
    op.drop_column('leads', 'next_follow_up_at')
    # ### end Alembic commands ###
